In [1]:
import numpy as np

In [3]:
val1=np.array([[7,0,2,1],
               [1,7,1,2],
               [8,1,12,6],
               [1,9,2,8]])
val1

array([[ 7,  0,  2,  1],
       [ 1,  7,  1,  2],
       [ 8,  1, 12,  6],
       [ 1,  9,  2,  8]])

In [4]:
val2=np.array([[13,0,4,0],
               [1,14,1,2],
               [1,0,12,3],
               [2,3,0,12]])
val2

array([[13,  0,  4,  0],
       [ 1, 14,  1,  2],
       [ 1,  0, 12,  3],
       [ 2,  3,  0, 12]])

In [5]:
val3=np.array([[14,1,2,0],
               [1,11,0,8],
               [1,1,14,2],
               [1,4,1,7]])
val3

array([[14,  1,  2,  0],
       [ 1, 11,  0,  8],
       [ 1,  1, 14,  2],
       [ 1,  4,  1,  7]])

In [6]:
val4=np.array([[12,0,2,0],
               [2,12,0,8],
               [3,2,14,4],
               [0,3,1,5]])
val4

array([[12,  0,  2,  0],
       [ 2, 12,  0,  8],
       [ 3,  2, 14,  4],
       [ 0,  3,  1,  5]])

In [8]:
val5=np.array([[8,3,4,1],
               [6,8,0,5],
               [0,0,12,0],
               [3,8,1,11]])
val5

array([[ 8,  3,  4,  1],
       [ 6,  8,  0,  5],
       [ 0,  0, 12,  0],
       [ 3,  8,  1, 11]])

68

In [18]:
y=[]
for i in [val1,val2,val3,val4,val5]:
    score=0
    for j in range(4):
        score+=i[j][j]
        score+=i[(j+2)%4][j]
    y.append(score/sum(sum(i)))

In [19]:
y

[0.8088235294117647,
 0.8970588235294118,
 0.8970588235294118,
 0.8676470588235294,
 0.8]

In [ ]:
impo

In [15]:
score=0
for i in range(4):
    score+=val2[i][i]
    score+=val2[(i+2)%4][i]
score/sum(sum(val2))*100

89.70588235294117